<?xml version="1.0"?>
<package format="3">
  <name>argo</name>
  <version>0.0.1</version>
  <description>The argo robot sailboat package</description>

  <maintainer email="tobi@ini.uzh.ch">Tobi Delbruck</maintainer>
  <author email="tobi@ini.uzh.ch">Tobi Delbruck</author>
  <author email="ikertesz@student.ethz.ch">Imre Kertesz</author>
  <author>Andrea Mock Caceres,Imre Kertesz,Tobi Delbruck</author>

  <license>BSD</license>

  <url type="website">https://github.com/SensorsINI/argo.git</url>

  <!-- ROS2 build tools -->
  <buildtool_depend>ament_python</buildtool_depend>

  <!-- ROS2 dependencies -->
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>

  <!-- Python dependencies -->
  <exec_depend>python3-smbus2</exec_depend>
  <exec_depend>python3-serial</exec_depend>
  <exec_depend>python3-numpy</exec_depend>

  <!-- Test dependencies -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

</package>
