/**:
  ros__parameters:
    argo:
      mode: autonomous
    simulation:
      publish_rate: 2.0
      simulation_rate: 10.0
      heading_trail_limit: 100
      grounding_behavior: reset
      exit_confirmation: true
      wind:
        wind_min_speed: 2.0
        wind_max_speed: 10.0
        wind_direction: 300.0
        wind_max_delta_percent: 0.0
        wind_gust_probability: 0.0
        wind_gust_min_duration: 3.0
        wind_gust_max_duration: 20.0
        wind_gust_min_speed: 4.0
        wind_gust_max_speed: 7.0
        wind_gust_max_delta_percent: 10.0
controller_node:
  ros__parameters:
    controller_type: patrol
    data_collection_enabled: false
    rudder_gain: 0.3
    rudder_full_scale_deg: 60.0
    param_file_path: argo.yaml
    patrol_lookahead_time: 15.0
    boundary_turn_threshold: 8.0
    tack_angle: 90.0
    broad_reach_angle: 110.0
    geofence_map_name: Argo Irchel pond sailing area
rudder_sail_radio_node:
  ros__parameters:
    human_override_timeout: 5.0
    deadband_threshold: 0.1875
    safety_max_rudder: 1.0
    safety_max_sail: 1.0
    param_file_path: argo.yaml
argo_boat_visualization:
  ros__parameters:
    visualization_scale: 6.0
