#!/bin/bash

echo "🚢 Argo Robot Control Commands"
echo "============================"
echo ""
echo "Service Control:"
echo "  al   - Launch argo service"
echo "  aq   - Quit argo service"
echo "  ars  - Restart argo service"
echo "  as   - Show service status"
echo ""
echo "Recording Control:"
echo "  ar   - Record data"
echo "  ac   - Close recording"
echo ""
echo "Help:"
echo "  argo_help - Show this help"
echo ""
echo "Full Makefile commands: make help"
