#!/bin/bash

echo "🚢 Argo Robot Control Commands"
echo "=================================="

echo "Direct Commands:"
echo "  python3 launch/argo_lifecycle_manager.py status   # Show status"
echo "  python3 launch/argo_lifecycle_manager.py monitor  # Monitor mode"
echo "  python3 launch/argo_lifecycle_manager.py simulate_local   # Start local simulation"
echo "  python3 launch/argo_lifecycle_manager.py simulate_remote  # Start remote simulation"

echo "Help:"
echo "  argo_help - Show this help"
echo "  make help - Show full Makefile commands"

echo "Service Control:"
echo "  al   - Launch argo service (start all nodes)"
echo "  aq   - Quit argo service (stop all nodes)"
echo "  ars              - Restart all launch nodes (aq && al)"
echo "  ars <node>       - Start one node if not running (e.g. ars anem, ars gps)"
echo "  ars <node> --restart - Stop and start that node again"
echo "  as   - Show service status"
echo "  am   - Monitor mode (watch for failures)"
echo "  alog - Follow argo launch logs"
echo "  adevcheck - Check for expected hardware devices"
echo ""
echo "Status Queries:"
echo "  abat    - Get battery status (formatted JSON)"
echo "  ahealth - Get health monitor status (formatted JSON)"
echo ""
echo "Battery / Power:"
echo "  astore  - Toggle storage rundown (enable/disable discharge to 7.6V then shut down; mode cleared on reboot)"
echo ""
echo "Hardware Diagnostics:"
echo "  ai2c       - Scan I2C buses (timing) + IMU ROS live (/imu_health, /imu) when 0x4a present"
echo "  ai2creset  - Reset I2C bus (stops services, resets bus, restarts services)"
echo "  abeep      - Pulse buzzer (default 0.5s, optional duration argument)"

echo "Simulation:"
echo "  asim      - Start argo in LOCAL simulation mode"
echo "  asimr     - Start argo in REMOTE simulation mode"
echo "  asimreset - Reset simulation to origin/home location"
echo "  asimkb    - Start keyboard control for simulation"
echo ""
echo "  💡 TIP: To keep markers visible after simulation ends:"
echo "     - Use Ctrl+Z to pause simulation before stopping"
echo "     - Or record with ros2 bag and playback for analysis"

echo "Recording Control:"
echo "  ar   - Start data recording"
echo "  ac   - Stop data recording"
echo "  apb  - Play back latest recording with visualization"
echo "  arr  - Re-record latest recording with visualization markers (for Foxglove import)"

echo "GUI Control:"
echo "  ag   - Launch Argo CLI GUI (interactive control)"

echo "Examples:"
echo "  al && as    # Start service and check status"
echo "  ar && ac    # Start and stop recording"
echo "  am          # Monitor for node failures"
